@startuml
skinparam shadowing false
skinparam backgroundColor #LightGrey
skinparam handwritten false

participant Alice

box "Everscale" #LightBlue
participant Repository
participant Game
participant NFT
end box

participant Bob

Alice -> Alice: <generate> **notice**
activate Alice
Alice -> Alice: <make> **chose (S|E|W)**
Alice -> Game: <bet> **sha256** of **chose+notice** (mint NFT)
activate Game #LightSalmon
Game -> NFT: <mint> **create NFT**
activate NFT #LightSalmon
NFT -> NFT: <mint> **created NFT for Game**
NFT -> Game: <???>
deactivate NFT
Alice -> Alice: <encrypt> **notice**
Alice <-> Repository: <send> **encrypted notice**
activate Repository #LightSalmon
Bob <-> NFT: <list> **list NFT**
activate Bob
Bob <-> Game: <beat> **chose (S|E|W)**
Alice <-> Game: <get> **status game**

Alice <-> Repository: <get> **encrypted notice**
Alice -> Alice: <decipher> **notice**
Alice -> Game: <send> **chose+notice** (end game)

alt Alice win case
    Game -> Alice: <transfer> **reward=bank-rake**
    Game -> NFT: <transfer> **Make Alice of NFT**
else Bob win case
    Game -> Bob: <transfer> **reward=bank-rake**
    Game -> NFT: <transfer> **Make Bob of NFT**
    deactivate Bob
else Standoff case
    Game -> Alice: <transfer> **reward=(bank-rake)/2**
    Game -> Bob: <transfer> **reward=(bank-rake)/2**
    Game -> NFT: <burn> **Delete NFT**
end

deactivate Game
Alice <-> Repository: <delete> **encrypted notice**
deactivate Alice
deactivate Repository
@enduml
