@startuml
skinparam shadowing false
skinparam backgroundColor #LightGrey
skinparam handwritten false

participant Alice

box "Everscale" #LightBlue
participant Vault
participant Game
participant NFT
end box

participant Bob

Alice -> Alice: <generate> **notice**
activate Alice
Alice -> Alice: <make> **chose (S|E|W)**
Alice -> Game: <bet> **sha256** of **chose+notice** (mint NFT)
activate Game #LightSalmon
Game -> NFT: <mint> **create NFT**
activate NFT #LightSalmon
NFT -> NFT: <mint> **created NFT for Game**
NFT -> Game: <status>
deactivate NFT
Alice -> Alice: <encrypt> **notice**
Alice <-> Vault: <send> **encrypted notice**
activate Vault #LightSalmon
Bob <-> NFT: <list> **list NFT**
activate Bob
Bob <-> Game: <beat> **chose (S|E|W)**
Alice <-> Game: <get> **status game**

Alice <-> Vault: <get> **encrypted notice**
Alice -> Alice: <decipher> **notice**
Alice -> Game: <send> **chose+notice** (end game)
Alice <-> Vault: <delete> **encrypted notice**
deactivate Vault
alt Standoff case
    Game -> Alice: <transfer> **reward=(bank-rake)/2**
    Game -> Bob: <transfer> **reward=(bank-rake)/2**
    Game -> NFT: <burn> **Delete NFT**
else Alice win case
    Game -> Alice: <transfer> **reward=bank-rake**
    deactivate Alice
    Game -> NFT: <transfer> **Make Alice owner of NFT**
else Bob win case
    Game -> Bob: <transfer> **reward=bank-rake**
    deactivate Bob
    Game -> NFT: <transfer> **Make Bob owner of NFT**
    deactivate Game
end
@enduml
